### ISSUE TITLE
GnuPG portable, nothing happens

### ISSUE THREAD

**Issue by AdKiller** [portapps/gnupg-portable#22]
### Behaviour

Nothing happens after opening gnupg-portable.exe and clicking yes or no in "Would you like to set GNUPGHOME in your environment?"

Gets stuck in the background with no way to close it normally.

In Windows PowerShell, GNUPGHOME is not recognized.

#### Expected behaviour

Some indication that something has happened.
Some way of closing the portable app and reverting changes.

#### Actual behaviour

The popup closes and then, nothing.

### Configuration

gnupg-portable-win32-2.2.26-9

Operating system Windows 10 Pro 64 bits 1909

**Winver screenshot** 

![image](https://user-images.githubusercontent.com/13304436/104315627-88863580-54db-11eb-98d0-7e17bc108384.png)

### Logs

[gnupg-portable.log](https://github.com/portapps/gnupg-portable/files/5802117/gnupg-portable.log)

**Comment by crazy-max** [comment]
@AdKiller 

> Nothing happens after opening gnupg-portable.exe and clicking yes or no in "Would you like to set GNUPGHOME in your environment?"

It's explained on the [homepage](https://portapps.io/app/gnupg-portable/#infos):

> This portapp is a self-extracting package and does not launch anything.

**Comment by renegade2k** [comment]
Am I missing something?
Downloaded the portable app (zip archive). 
Unzipped it.
Started _gnupg-portable.exe_ (just as the homepage says).
It asks me to add the environment variable to Windows. I agreed.
After this (again as homepage says) change the variable to _`data\.gnupg`_ and also check the yaml file for silent variable to be false.
Again starting _gnupg-portable.exe_ and it asts me again for setting the environment variable.
Nothing else happens...

How this app is supposed to work?

**Comment by Shohreh** [comment]
> Am I missing something? Downloaded the portable app (zip archive). Unzipped it. Started _gnupg-portable.exe_ (just as the homepage says). It asks me to add the environment variable to Windows. I agreed. After this (again as homepage says) change the variable to _`data\.gnupg`_ and also check the yaml file for silent variable to be false. Again starting _gnupg-portable.exe_ and it asts me again for setting the environment variable. Nothing else happens...
> 
> How this app is supposed to work?

Same here. I don't understand what gnupg-portable.exe is for. Nothing happens after clicking "Yes" on "Would you like to set GNUPGHOME in your environment ?". I guess we just have to use .\app\bin\gpg.exe.
